/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef TERAHFSS_TEXTCLICK_7_PRIVATE_H
#define TERAHFSS_TEXTCLICK_7_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.0.0.1"
#define VER_MAJOR	1
#define VER_MINOR	0
#define VER_RELEASE	0
#define VER_BUILD	1
#define COMPANY_NAME	""
#define FILE_VERSION	"1.0.0.1"
#define FILE_DESCRIPTION	"TeraHFSS TextClick 7"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"TeraHFSS TextClick 7"
#define PRODUCT_VERSION	"1.0.0.1"

#endif /*TERAHFSS_TEXTCLICK_7_PRIVATE_H*/
